name: Terraform CI CD Pipeline for Deploying AWS Resources
run-name: ${{ github.actor }} has triggered the pipeline

on:
  push:
    branches:
      - "master"
 

jobs:
  build-infra:
    name: terraform-ci-cd
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume:	arn:aws:iam::975050300181:role/test-GitHubActionsServiceRole-bx1JXkvsF7rR
          aws-region: us-east-1
      - name: Add SSH key
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p /home/runner/.ssh
          ssh-keyscan github.com >> /home/runner/.ssh/known_hosts
          echo "${{ secrets.ssh_key}}" > /home/runner/.ssh/github_actions
          ls -l /home/runner/.ssh/github_actions
          cat /home/runner/.ssh/github_actions
          chmod 600 /home/runner/.ssh/github_actions
          ssh-keygen -p -f /home/runner/.ssh/github_actions
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add /home/runner/.ssh/github_actions
          pwd
          ls -l
          cd /home/runner/work/vpc/vpc/Terraform-VPC/modules
          terraform init
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform Init
        id: init
        working-directory: ./Terraform-VPC/modules
        run: |
  
          pwd
          ls -l
          terraform init
      
      - name: Terraform Validate
        id: validate
        run: terraform validate
        working-directory: ./Terraform-VPC/modules
      - name: Terraform Plan
        id: plan
        run: terraform plan
        working-directory: ./Terraform-VPC/modules
      - name: Terraform Apply
        id: apply
        run: terraform apply --auto-approve
        working-directory: ./Terraform-VPC/modules
