name: Terraform CI CD Pipeline for Deploying AWS Resources
run-name: ${{ github.actor }} has triggered the pipeline

on:
  push:
    branches:
      - "master"
 

permissions:
      id-token: write
      contents: read
      
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
          client-id: 'e65bf60d-d1bd-46ca-a5b8-1a5070f992ad'
          tenant-id: '26fff28c-a1e5-41eb-9b25-335a0d48ccfb'
          subscription-id: 'f644f259-67c5-448c-bfae-3e2f4367894d'
  
    - name: 'Run Azure CLI commands'
      run: |
          az account show
          az group list
          pwd 
