name: Terraform CI CD Pipeline for Deploying AWS Resources
run-name: ${{ github.actor }} has triggered the pipeline

on:
  workflow_dispatch
 

jobs:
  build-infra:
    name: terraform-ci-cd
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume:	arn:aws:iam::975050300181:role/test-GitHubActionsServiceRole-bx1JXkvsF7rR
          aws-region: us-east-1
      - name: Setup SSH Keys and known_hosts
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          #  Copied from https://github.com/maddox/actions/blob/master/ssh/entrypoint.sh
        run: |
          SSH_PATH="$HOME/.ssh"

          mkdir -p "$SSH_PATH"
          touch "$SSH_PATH/known_hosts"

         echo "$PRIVATE_KEY" > "$SSH_PATH/id_rsa"

         chmod 700 "$SSH_PATH"
         ssh-keyscan github.com >> ~/.ssh/known_hosts
         chmod 600 "$SSH_PATH/known_hosts"
         chmod 600 "$SSH_PATH/id_rsa"

      eval $(ssh-agent)
      ssh-add "$SSH_PATH/id_rsa"
    
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ./Terraform-VPC/modules
      - name: Terraform Validate
        id: validate
        run: terraform validate
        working-directory: ./Terraform-VPC/modules
      - name: Terraform Plan
        id: plan
        run: terraform plan
        working-directory: ./Terraform-VPC/modules
      - name: Terraform Apply
        id: apply
        run: terraform apply --auto-approve
        working-directory: ./Terraform-VPC/modules
